name: prometheus
title: Prometheus
icon: prometheus

services:
- name: prometheus
  title: Prometheus
  service: prometheus
  main: true
  volumes:
  - name: data
    size: 10
- name: grafana
  title: Grafana
  service: grafana
  disabled: true
  links:
  - name: prometheus
    service: prometheus
  configs:
  - name: datasources
    config: configs/grafana-datasources.yml.tmpl
  volumes:
  - name: data
    size: 10
  workloads:
  - name: main
    containers:
    - name: grafana
      resources:
        request:
          cpu: 200
          memory: 512
        limit:
          cpu: 1000
          memory: 1024
